CREATE FUNCTION ufn_GetSalaryLevel(@Salary DECIMAL(18,4))
RETURNS VARCHAR(20)
AS
BEGIN
	IF @Salary < 30000
		RETURN 'Low'
	ELSE IF @Salary BETWEEN 30000 AND 50000 
		RETURN 'Average'
	ELSE
		RETURN 'High'

	RETURN NULL
END