/*CREATE DATABASE SoftUni*/

USE SoftUni

CREATE TABLE Towns
(
	Id SMALLINT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Addresses
(
	Id SMALLINT PRIMARY KEY IDENTITY,
	AddressText NVARCHAR(200) NOT NULL,
	TownId SMALLINT FOREIGN KEY REFERENCES Towns(Id) NOT NULL
)

CREATE TABLE Departments
(
	Id SMALLINT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(100) NOT NULL,
)

CREATE TABLE Employees
(
	Id SMALLINT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(50) NOT NULL,
	MiddleName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	JobTitle NVARCHAR(100) NOT NULL,
	DepartmentId SMALLINT FOREIGN KEY REFERENCES Departments(Id) NOT NULL,
	HireDate DATE,
	Salary DECIMAL(8,2),
	AddressId SMALLINT FOREIGN KEY REFERENCES Addresses(Id) NOT NULL
)